import type { Player, Season } from "../types";

export const mockPlayers: Player[] = [
  {
    id: 1,
    firstName: "Miguel Ángel",
    lastName: "Merentiel Serrano",
    dateOfBirth: "1994-06-14",
    nationality: "Uruguay",
    position: "SS",
    photoUrl: null,
    teamId: 1,
    team: {
      id: 1,
      name: "CA Boca Juniors",
      country: "Argentina",
      logoUrl: null,
    },
    stats: [
      {
        id: 1,
        seasonId: 1,
        season: { id: 1, name: "2026" },
        matchesPlayed: 10,
        minutesPlayed: 754,
        goals: 4,
        assists: 2,
        yellowCards: 1,
        redCards: 0,
        shotsOnTarget: 14,
        successfulPasses: 84,
        passAccuracy: 76.4,
        aerialDuelsWon: 22,
        aerialDuelsTotal: 73,
        defensiveDuelsWon: 19,
        defensiveDuelsTotal: 32,
        xG: 3.0,
        xA: 1.6,
        recoveries: 15,
        heatmapGrid: null,
      },
    ],
  },
  {
    id: 2,
    firstName: "Facundo",
    lastName: "Colidio",
    dateOfBirth: "2000-01-04",
    nationality: "Argentina",
    position: "LW",
    photoUrl: null,
    teamId: 2,
    team: {
      id: 2,
      name: "CA River Plate",
      country: "Argentina",
      logoUrl: null,
    },
    stats: [
      {
        id: 2,
        seasonId: 1,
        season: { id: 1, name: "2026" },
        matchesPlayed: 9,
        minutesPlayed: 534,
        goals: 2,
        assists: 1,
        yellowCards: 1,
        redCards: 0,
        shotsOnTarget: 12,
        successfulPasses: 96,
        passAccuracy: 73.3,
        aerialDuelsWon: 25,
        aerialDuelsTotal: 86,
        defensiveDuelsWon: 46,
        defensiveDuelsTotal: 97,
        xG: 1.8,
        xA: 0.8,
        recoveries: 91,
        heatmapGrid: null,
      },
    ],
  },
];

export const mockSeasons: Season[] = [
  { id: 3, name: "2026" },
  { id: 2, name: "2025" },
  { id: 1, name: "2024" },
];